 const  studentData=[ 
      {
     
      name:"Stephany",
      class:'8th',
      result:'Passed',
      score:"78/100",
      grade:'Excellent',
   
      },
      {
      name:"Deepak",
      class:'6th',
      result:'Passed',
      score:"80/100",
      grade:'Average',
},
      {
            name:"Justin",
            class:'5th',
            result:'Passed',
            score:"68/100",
            grade:'Excellent',
      },    
      {
            name:"Omega",
            class:'8th',
            result:'Passed',
            score:"58/100",
            grade:'Excellent',
      },
      {
            name:"Shadow",
            class:'6th',
            result:'Failed',
            score:"24/100",
            grade:'Poor',
      },
      {
            name:"Rocky",
            class:'8th',
            result:'Passed',
            score:"78/100",
            grade:'Excellent',
      },
      {
            name:"Albert",
            class:'9th',
            result:'Passed',
            score:"98/100",
            grade:'Excellent',
      }
]
export default studentData;