 const  studentData=[ 
      {
     
      name:"Stephany",
      clasess:'8th',
      result:'Passed',
      score:"78/100",
      grade:'Excellent',
   
      },
      {
      name:"Deepak",
      clasess:'6th',
      result:'Passed',
      score:"80/100",
      grade:'Average',
},
      {
            name:"Justin",
            clasess:'5th',
            result:'Passed',
            score:"68/100",
            grade:'Excellent',
      },    
      {
            name:"Omega",
            clasess:'8th',
            result:'Passed',
            score:"58/100",
            grade:'Excellent',
      },
      {
            name:"Shadow",
            clasess:'6th',
            result:'Failed',
            score:"24/100",
            grade:'Poor',
      },
      {
            name:"Rocky",
            clasess:'8th',
            result:'Passed',
            score:"78/100",
            grade:'Excellent',
      },
      {
            name:"Albert",
            clasess:'9th',
            result:'Passed',
            score:"98/100",
            grade:'Excellent',
      }
]
export default studentData;